### PR TITLE
Fix:  Short version of "dry run" option yields an error #88 

### PR DESCRIPTION
**Pull request by inirudebwoy**
Hi,

I fixed the issue https://github.com/peritus/bumpversion/issues/88. It also was reproducible with '-m' flag. What do you think?

### CODE REVIEW

**Comment by peritus** [comment]
Thanks for the fix!

I'd probably add a regression test to this before merging.

**Comment by inirudebwoy** [comment]
Ok, I will update this PR with some tests.

**Comment by peritus** [comment]
Just one demonstrating the issue would do. Thanks a lot!

**Comment by inirudebwoy** [comment]
I have added few tests for function split_args_in_optional_and_positional.

**Comment by peritus** [comment]
I just commited your patch without the whitespace changes as 6ec908f018a827bfae94ed50baf241461eba7bcb to master.

Your contribution is highly appreciated, thanks!

**Pull request closed without merging**
